PocketManager: Initialize Handler with MainLooper
When PocketManager is instantiated via getSystemService on background worker
threads (such as SystemUIBg in SystemUIDeviceEntryFaceAuthInteractor),
new Handler() without a specified Looper throws a RuntimeException because
Looper.prepare() has not been called on the worker thread:

    java.lang.RuntimeException: Can't create handler inside thread Thread[SystemUIBg-3,5,main] that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:263)
        at android.os.Handler.<init>(Handler.java:165)
        at android.pocket.PocketManager.<init>(PocketManager.java:101)

Initialize mHandler with Looper.getMainLooper() so PocketManager can safely
be constructed on any thread. Also mark isDeviceInPocket as volatile in
SystemUIDeviceEntryFaceAuthInteractor for thread-safe cross-thread access.

Change-Id: I62c64106031f2bc0d9ff0c21a57ec5e6c714d5cc